# Executive Summary

An Artificial Neural Network was developed to determine a bank’s probability of member retention (current and future). This predictive model used the bank’s historical data (credit score, gender, geographic location, bank tenure, balance, credit card, active status, etc.) and Python (Keras backed by TensorFlow, Scikit-Learn and Pandas) to analyze and structure the data set.

## Model Performance

The accuracy in the model for the training set was calculated at 83.7% and 84.3% for the testing set. The model was optimized by hyper parameter tunning. This tunning was able to increase the training set accuracy to 85%.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

%matplotlib inline

In [4]:
#Uploading data set of members
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
#Structuring data set
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
labelencoder_x_1=LabelEncoder()
x[:,1]=labelencoder_x_1.fit_transform(x[:,1])
labelencoder_x_2=LabelEncoder()
x[:,2]=labelencoder_x_2.fit_transform(x[:,2])
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()
x=x[:,1:]
x=pd.DataFrame(x)

In [8]:
#Splitting data set into training and test sets
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [9]:
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [10]:
#Importing the Keras libraries and packages. 
#Keras will be using TesorFlow as a backend.
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.


In [13]:
#The Artificial Neural Network portion of the model
#The Input, Hidden and Output Layers are being developed
classifier=Sequential()
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))


In [14]:
#Compiling the ANN
#The descent and loss conditions will be added. 
#In this case it will be Stochastic Gradient descent and Logarithmic Loss.
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [15]:
#THe model is analyzing the train sets
#Without doing a optimization analysis of the code the accuracy from the training set is 0.8354
classifier.fit(xtrain,ytrain,batch_size=10,epochs=20)

Epoch 1/20
8000/8000 [==============================] - 5s 615us/step - loss: 0.4841 - acc: 0.7926
Epoch 2/20
8000/8000 [==============================] - 4s 500us/step - loss: 0.4285 - acc: 0.7926
Epoch 3/20
8000/8000 [==============================] - 4s 520us/step - loss: 0.4229 - acc: 0.8045
Epoch 4/20
8000/8000 [==============================] - 3s 431us/step - loss: 0.4186 - acc: 0.8221
Epoch 5/20
8000/8000 [==============================] - 3s 408us/step - loss: 0.4164 - acc: 0.8281
Epoch 6/20
8000/8000 [==============================] - 3s 435us/step - loss: 0.4144 - acc: 0.8292
Epoch 7/20
8000/8000 [==============================] - 3s 384us/step - loss: 0.4128 - acc: 0.8320
Epoch 8/20
8000/8000 [==============================] - 3s 390us/step - loss: 0.4114 - acc: 0.8316
Epoch 9/20
8000/8000 [==============================] - 3s 389us/step - loss: 0.4106 - acc: 0.8327
Epoch 10/20
8000/8000 [==============================] - 3s 387us/step - loss: 0.4097 - acc: 0.8327
Epoch 11/

In [16]:
ypred=classifier.predict(xtest)
ypred

array([[ 0.09427074],
       [ 0.03724562],
       [ 0.07489113],
       ..., 
       [ 0.83345568],
       [ 0.69152105],
       [ 0.40373838]], dtype=float32)

In [17]:
ypred=(ypred>0.5)
ypred

array([[False],
       [False],
       [False],
       ..., 
       [ True],
       [ True],
       [False]], dtype=bool)

In [18]:
#Without doing a optimization analysis of the code the accuracy from the test set is 0.84
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,ypred)
cm

array([[1580,   42],
       [ 272,  106]], dtype=int64)

In [19]:
np.around(((cm[0,0]+cm[1,1])/2000),decimals=3)

0.84299999999999997

In [20]:
#New Member single prediction using random values. 
#The model correctly predicted that the new member was likely to stay.
newpred=classifier.predict(sc.transform(np.array([[0.0,0,600,1,40,3,60000,2,1,1,50000]])))
newpred=(newpred>0.5)
newpred

array([[False]], dtype=bool)

In [21]:
check=pd.DataFrame(x)
check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
0     10000 non-null float64
1     10000 non-null float64
2     10000 non-null float64
3     10000 non-null float64
4     10000 non-null float64
5     10000 non-null float64
6     10000 non-null float64
7     10000 non-null float64
8     10000 non-null float64
9     10000 non-null float64
10    10000 non-null float64
dtypes: float64(11)
memory usage: 859.5 KB


In [262]:
#Optimizing the model by evaluating different hyper parameters 
#To prevent overfitting the dropout function has been included
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [274]:
def build_classifier(optimizer):
    classifier=Sequential()
    classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))
    classifier.add(Dropout(rate=0.1))
    classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
    classifier.add(Dropout(rate=0.1))
    classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))
    classifier.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])   
    return classifier

In [275]:
classifier=KerasClassifier(build_fn=build_classifier)
parameters={'batch_size': [25,32],'epochs':[100,500],'optimizer': ['adam','rmsprop']}
grid_search=GridSearchCV(estimator=classifier,param_grid=parameters,scoring='accuracy',cv=10)

In [ ]:
grid_search=grid_search.fit(xtrain,ytrain)

In [ ]:
#Determining the best hyper parameters and highest accuracy
best_parameter=grid_search.best_params_
best_accuracy=grid_search.best_score_

In [ ]:
best_accuracy

In [ ]:
best_parameter